// <auto-generated>
using CodeGenHero.EAMVCXamPOCO.Interface;
using MSC.BingoBuzz.Repository.Entities.BB;
using System.Linq;

namespace MSC.BingoBuzz.Repository.Interface
{
	public interface IBBRepositoryCrud : 
		ICRUDOperation<BingoContent>,
		ICRUDOperation<BingoInstance>,
		ICRUDOperation<BingoInstanceContent>,
		ICRUDOperation<BingoInstanceEvent>,
		ICRUDOperation<BingoInstanceEventType>,
		ICRUDOperation<Company>,
		ICRUDOperation<FrequencyType>,
		ICRUDOperation<Meeting>,
		ICRUDOperation<MeetingAttendee>,
		ICRUDOperation<MeetingSchedule>,
		ICRUDOperation<NotificationMethodType>,
		ICRUDOperation<NotificationRule>,
		ICRUDOperation<RecurrenceRule>,
		ICRUDOperation<User>
	{

		#region GetQueryable

		IQueryable<BingoContent> GetQueryableBingoContent();
		IQueryable<BingoInstance> GetQueryableBingoInstance();
		IQueryable<BingoInstanceContent> GetQueryableBingoInstanceContent();
		IQueryable<BingoInstanceEvent> GetQueryableBingoInstanceEvent();
		IQueryable<BingoInstanceEventType> GetQueryableBingoInstanceEventType();
		IQueryable<Company> GetQueryableCompany();
		IQueryable<FrequencyType> GetQueryableFrequencyType();
		IQueryable<Meeting> GetQueryableMeeting();
		IQueryable<MeetingAttendee> GetQueryableMeetingAttendee();
		IQueryable<MeetingSchedule> GetQueryableMeetingSchedule();
		IQueryable<NotificationMethodType> GetQueryableNotificationMethodType();
		IQueryable<NotificationRule> GetQueryableNotificationRule();
		IQueryable<RecurrenceRule> GetQueryableRecurrenceRule();
		IQueryable<User> GetQueryableUser();

		#endregion

	}
}
