// <auto-generated> - Template:DTO, Version:1.0, Id:58fa7ee2-89f7-41e6-85ed-8d4482653990
namespace CodeGenHero.BingoBuzz.DTO.BB
{
	public partial class BingoInstance
	{
		public BingoInstance()
		{
			BingoInstanceContents = new System.Collections.Generic.List<BingoInstanceContent>();
			BingoInstanceEvents = new System.Collections.Generic.List<BingoInstanceEvent>();

			InitializePartial();
		}

		public System.Guid BingoInstanceId { get; set; } // Primary key
		public System.Guid? MeetingId { get; set; }
		public int NumberOfColumns { get; set; }
		public int NumberOfRows { get; set; }
		public bool IncludeFreeSquareIndicator { get; set; }
		public int BingoInstanceStatusTypeId { get; set; }
		public System.DateTime CreatedDate { get; set; }
		public System.Guid CreatedUserId { get; set; }
		public System.DateTime UpdatedDate { get; set; }
		public System.Guid UpdatedUserId { get; set; }
		public bool IsDeleted { get; set; }
		public virtual System.Collections.Generic.ICollection<BingoInstanceContent> BingoInstanceContents { get; set; } // Many to many mapping
		public virtual System.Collections.Generic.ICollection<BingoInstanceEvent> BingoInstanceEvents { get; set; } // Many to many mapping
		public virtual BingoInstanceStatusType BingoInstanceStatusType { get; set; } 
		public virtual Meeting Meeting { get; set; } 
		public virtual User CreatedUser { get; set; } 
		public virtual User UpdatedUser { get; set; } 


		partial void InitializePartial();

	}
}
