// <auto-generated> - Template:DTO, Version:1.1, Id:58fa7ee2-89f7-41e6-85ed-8d4482653990
namespace CodeGenHero.BingoBuzz.DTO.BB
{
	public partial class BingoContent
	{
		public BingoContent()
		{
			InitializePartial();
		}

		public System.Guid BingoContentId { get; set; } // Primary key
		public string Content { get; set; }
		public bool FreeSquareIndicator { get; set; }
		public int NumberOfUpvotes { get; set; }
		public int NumberOfDownvotes { get; set; }
		public System.DateTime CreatedDate { get; set; }
		public System.Guid CreatedUserId { get; set; }
		public System.DateTime UpdatedDate { get; set; }
		public System.Guid UpdatedUserId { get; set; }
		public bool IsDeleted { get; set; }
		// public virtual System.Collections.Generic.ICollection<BingoInstanceContent> BingoInstanceContents { get; set; } // Many to many mapping -- Excluded navigation property per configuration.
		public virtual User CreatedUser { get; set; } 
		public virtual User UpdatedUser { get; set; } 


		partial void InitializePartial();

	}
}
