// <auto-generated> - Template:DTO, Version:1.0, Id:58fa7ee2-89f7-41e6-85ed-8d4482653990
namespace CodeGenHero.BingoBuzz.DTO.BB
{
	public partial class FrequencyType
	{
		public FrequencyType()
		{
			RecurrenceRules = new System.Collections.Generic.List<RecurrenceRule>();

			InitializePartial();
		}

		public int FrequencyTypeId { get; set; } // Primary key
		public string Name { get; set; }
		public virtual System.Collections.Generic.ICollection<RecurrenceRule> RecurrenceRules { get; set; } // Many to many mapping


		partial void InitializePartial();

	}
}
