// <auto-generated> - Template:DTO, Version:1.1, Id:58fa7ee2-89f7-41e6-85ed-8d4482653990
namespace CodeGenHero.BingoBuzz.DTO.BB
{
	public partial class NotificationMethodType
	{
		public NotificationMethodType()
		{
			InitializePartial();
		}

		public int NotificationMethodTypeId { get; set; } // Primary key
		public string Name { get; set; }
		// public virtual System.Collections.Generic.ICollection<NotificationRule> NotificationRules { get; set; } // Many to many mapping -- Excluded navigation property per configuration.


		partial void InitializePartial();

	}
}
