// <auto-generated> - Template:XamSample, Version:1.1, Id:9131a0a2-7ceb-4f4c-b8a9-6740ac19f66c
using System;
using CodeGenHero.BingoBuzz.DTO.BB;

namespace CodeGenHero.BingoBuzz.DTO.BB
{
	public static class DemoBingoInstance
	{
		public static System.Guid SampleBingoInstanceId00 = Guid.Parse("aee7ab59-8ab7-4f3c-871e-e68fb7d03a7e");
		public static System.Guid SampleBingoInstanceId01 = Guid.Parse("04c52e05-ebb5-4811-b84c-e9ef2cc87ab2");

		public static BingoInstance SampleBingoInstance00
		{
			get
			{
				return new BingoInstance()
				{
					BingoInstanceId = SampleBingoInstanceId00,
					MeetingId = Guid.Parse("4a49de2a-8681-47c4-b61b-d89e25896f94"),
					NumberOfColumns = 0,
					NumberOfRows = 0,
					IncludeFreeSquareIndicator = false,
					BingoInstanceStatusTypeId = 0,
					CreatedDate = DateTime.Now,
					CreatedUserId = Guid.Parse("6c88ae45-3ea7-421c-bf99-f7835d087e2c"),
					UpdatedDate = DateTime.Now,
					UpdatedUserId = Guid.Parse("5ee064af-4e1d-499d-84a0-1578ed791b58"),
					IsDeleted = false,
				};
			}
		}
		public static BingoInstance SampleBingoInstance01
		{
			get
			{
				return new BingoInstance()
				{
					BingoInstanceId = SampleBingoInstanceId01,
					MeetingId = Guid.Parse("2f30b739-f339-405b-81d2-29278274e1e7"),
					NumberOfColumns = 0,
					NumberOfRows = 0,
					IncludeFreeSquareIndicator = false,
					BingoInstanceStatusTypeId = 0,
					CreatedDate = DateTime.Now,
					CreatedUserId = Guid.Parse("7c9c80d9-5496-4df8-b01a-6acdecc32ecb"),
					UpdatedDate = DateTime.Now,
					UpdatedUserId = Guid.Parse("8cae13ac-9a05-4f8e-b584-2eca95f08b10"),
					IsDeleted = false,
				};
			}
		}

	}
}
