// <auto-generated> - Template:XamSample, Version:1.1, Id:9131a0a2-7ceb-4f4c-b8a9-6740ac19f66c
using System;
using CodeGenHero.BingoBuzz.DTO.BB;

namespace CodeGenHero.BingoBuzz.DTO.BB
{
	public static class DemoBingoContent
	{
		public static System.Guid SampleBingoContentId00 = Guid.Parse("b20c5e67-2849-4d5e-be48-bf81aeb0d06e");
		public static System.Guid SampleBingoContentId01 = Guid.Parse("ece86cb0-79a6-4239-a841-8457780e0987");

		public static BingoContent SampleBingoContent00
		{
			get
			{
				return new BingoContent()
				{
					BingoContentId = SampleBingoContentId00,
					Content = "SampleContent",
					FreeSquareIndicator = false,
					NumberOfUpvotes = 0,
					NumberOfDownvotes = 0,
					CreatedDate = DateTime.Now,
					CreatedUserId = Guid.Parse("ce6c9d2f-a3f0-4bb1-b7f7-1b1a543d1eec"),
					UpdatedDate = DateTime.Now,
					UpdatedUserId = Guid.Parse("0835d9e7-e262-4dd3-9e20-6f507b71e3d5"),
					IsDeleted = false,
				};
			}
		}
		public static BingoContent SampleBingoContent01
		{
			get
			{
				return new BingoContent()
				{
					BingoContentId = SampleBingoContentId01,
					Content = "SampleContent",
					FreeSquareIndicator = false,
					NumberOfUpvotes = 0,
					NumberOfDownvotes = 0,
					CreatedDate = DateTime.Now,
					CreatedUserId = Guid.Parse("f42c9948-edc0-4e94-b452-e7569d7d9da8"),
					UpdatedDate = DateTime.Now,
					UpdatedUserId = Guid.Parse("e7b45981-4a1c-4025-b1d2-e0d73a50a6f5"),
					IsDeleted = false,
				};
			}
		}

	}
}
