// <auto-generated> - Template:XamSample, Version:1.0, Id:9131a0a2-7ceb-4f4c-b8a9-6740ac19f66c
using System;
using CodeGenHero.BingoBuzz.DTO.BB;

namespace CodeGenHero.BingoBuzz.Xam.ModelData.SampleXam
{
	public static class DemoBingoInstanceStatusType
		{
		public static int SampleBingoInstanceStatusTypeId00 = 1541850350;
		public static int SampleBingoInstanceStatusTypeId01 = 1541850350;

		public static BingoInstanceStatusType SampleBingoInstanceStatusType00
		{
			get
			{
				return new BingoInstanceStatusType()
				{
					BingoInstanceStatusTypeId = SampleBingoInstanceStatusTypeId00,
					Name = "SampleName",
				};
			}
		}
		public static BingoInstanceStatusType SampleBingoInstanceStatusType01
		{
			get
			{
				return new BingoInstanceStatusType()
				{
					BingoInstanceStatusTypeId = SampleBingoInstanceStatusTypeId01,
					Name = "SampleName",
				};
			}
		}

		}
	}

