// <auto-generated> - Template:XamSample, Version:1.1, Id:9131a0a2-7ceb-4f4c-b8a9-6740ac19f66c
using System;
using CodeGenHero.BingoBuzz.DTO.BB;

namespace CodeGenHero.BingoBuzz.DTO.BB
{
	public static class DemoBingoInstanceEventType
	{
		public static int SampleBingoInstanceEventTypeId00 = 547636407;
		public static int SampleBingoInstanceEventTypeId01 = 547636407;

		public static BingoInstanceEventType SampleBingoInstanceEventType00
		{
			get
			{
				return new BingoInstanceEventType()
				{
					BingoInstanceEventTypeId = SampleBingoInstanceEventTypeId00,
					Name = "SampleName",
				};
			}
		}
		public static BingoInstanceEventType SampleBingoInstanceEventType01
		{
			get
			{
				return new BingoInstanceEventType()
				{
					BingoInstanceEventTypeId = SampleBingoInstanceEventTypeId01,
					Name = "SampleName",
				};
			}
		}

	}
}
