// <auto-generated> - Template:XamSample, Version:1.1, Id:9131a0a2-7ceb-4f4c-b8a9-6740ac19f66c
using System;
using CodeGenHero.BingoBuzz.DTO.BB;

namespace CodeGenHero.BingoBuzz.DTO.BB
{
	public static class DemoCompany
	{
		public static System.Guid SampleCompanyId00 = Guid.Parse("28c21723-8fd3-4911-bf2f-046ef5809655");
		public static System.Guid SampleCompanyId01 = Guid.Parse("0f6e45df-f371-422f-ad0b-f9a0e527cbfd");

		public static Company SampleCompany00
		{
			get
			{
				return new Company()
				{
					CompanyId = SampleCompanyId00,
					Name = "SampleName",
					CodeName = "SampleCodeName",
					Address1 = "SampleAddress1",
					Address2 = "SampleAddress2",
					City = "SampleCity",
					State = "SampleState",
					Zip = "SampleZip",
					WebsiteUrl = "SampleWebsiteUrl",
					CreatedDate = DateTime.Now,
					CreatedUserId = Guid.Parse("0996427c-661e-42a6-b8ea-0eb79da3f856"),
					UpdatedDate = DateTime.Now,
					UpdatedUserId = Guid.Parse("2fd54a8b-c370-4f6d-888e-423a3659a222"),
					IsDeleted = false,
				};
			}
		}
		public static Company SampleCompany01
		{
			get
			{
				return new Company()
				{
					CompanyId = SampleCompanyId01,
					Name = "SampleName",
					CodeName = "SampleCodeName",
					Address1 = "SampleAddress1",
					Address2 = "SampleAddress2",
					City = "SampleCity",
					State = "SampleState",
					Zip = "SampleZip",
					WebsiteUrl = "SampleWebsiteUrl",
					CreatedDate = DateTime.Now,
					CreatedUserId = Guid.Parse("db2536f8-5ebe-4887-9bf8-6f1856349bab"),
					UpdatedDate = DateTime.Now,
					UpdatedUserId = Guid.Parse("aa9706ea-19f9-45f2-a4c5-d6e0e4f288f4"),
					IsDeleted = false,
				};
			}
		}

	}
}
