// <auto-generated> - Template:XamSample, Version:1.0, Id:9131a0a2-7ceb-4f4c-b8a9-6740ac19f66c
using System;
using CodeGenHero.BingoBuzz.DTO.BB;

namespace CodeGenHero.BingoBuzz.Xam.ModelData.SampleXam
{
	public static class DemoFrequencyType
		{
		public static int SampleFrequencyTypeId00 = 164894631;
		public static int SampleFrequencyTypeId01 = 164894631;

		public static FrequencyType SampleFrequencyType00
		{
			get
			{
				return new FrequencyType()
				{
					FrequencyTypeId = SampleFrequencyTypeId00,
					Name = "SampleName",
				};
			}
		}
		public static FrequencyType SampleFrequencyType01
		{
			get
			{
				return new FrequencyType()
				{
					FrequencyTypeId = SampleFrequencyTypeId01,
					Name = "SampleName",
				};
			}
		}

		}
	}

