// <auto-generated> - Template:XamSample, Version:1.0, Id:9131a0a2-7ceb-4f4c-b8a9-6740ac19f66c
using System;
using CodeGenHero.BingoBuzz.DTO.BB;

namespace CodeGenHero.BingoBuzz.Xam.ModelData.SampleXam
{
	public static class DemoMeetingAttendee
		{
		public static System.Guid SampleMeetingAttendeeId00 = Guid.Parse("5053945a-10d8-4658-9731-0d61df72fd99");
		public static System.Guid SampleMeetingAttendeeId01 = Guid.Parse("4ddcbfb4-63ae-48b8-aa39-698d8980d354");

		public static MeetingAttendee SampleMeetingAttendee00
		{
			get
			{
				return new MeetingAttendee()
				{
					MeetingAttendeeId = SampleMeetingAttendeeId00,
					MeetingId = Guid.Parse("5b68713e-2d4f-47c8-9477-e6cae694f041"),
					UserId = Guid.Parse("1e114f97-675a-4fbd-a6b5-cd9ae51ca849"),
					NotificationRuleId = Guid.Parse("d63c9035-1c93-4be7-aeb5-afbc75b6dd64"),
					CreatedDate = DateTime.Now,
					CreatedUserId = Guid.Parse("5c45a1fe-2ca2-4ac5-b6aa-2ca727bda19d"),
					UpdatedDate = DateTime.Now,
					UpdatedUserId = Guid.Parse("524fd607-ddbf-4f5a-b075-4c45d1ed3509"),
					IsDeleted = false,
				};
			}
		}
		public static MeetingAttendee SampleMeetingAttendee01
		{
			get
			{
				return new MeetingAttendee()
				{
					MeetingAttendeeId = SampleMeetingAttendeeId01,
					MeetingId = Guid.Parse("e5cb17b4-a2c5-42a8-bc12-bcc254c64460"),
					UserId = Guid.Parse("e63364e0-048c-4355-a908-4e469425efee"),
					NotificationRuleId = Guid.Parse("f9011832-572c-4e74-99b7-7be89ea1be5b"),
					CreatedDate = DateTime.Now,
					CreatedUserId = Guid.Parse("2c55da56-f7de-4bf1-944a-c023a446decf"),
					UpdatedDate = DateTime.Now,
					UpdatedUserId = Guid.Parse("87c7581d-88a5-4f2e-a984-3d6c463ef788"),
					IsDeleted = false,
				};
			}
		}

		}
	}

