// <auto-generated> - Template:XamSample, Version:1.0, Id:9131a0a2-7ceb-4f4c-b8a9-6740ac19f66c
using System;
using CodeGenHero.BingoBuzz.DTO.BB;

namespace CodeGenHero.BingoBuzz.DTO.BB
{
	public static class DemoNotificationRule
		{
		public static System.Guid SampleNotificationRuleId00 = Guid.Parse("9b258985-9ada-4e9c-8505-83d2eaba0911");
		public static System.Guid SampleNotificationRuleId01 = Guid.Parse("12bd29f2-5aec-4def-af86-81b46107a800");

		public static NotificationRule SampleNotificationRule00
		{
			get
			{
				return new NotificationRule()
				{
					NotificationRuleId = SampleNotificationRuleId00,
					NotificationMethodTypeId = 0,
					MinutesBeforehand = 0,
				};
			}
		}
		public static NotificationRule SampleNotificationRule01
		{
			get
			{
				return new NotificationRule()
				{
					NotificationRuleId = SampleNotificationRuleId01,
					NotificationMethodTypeId = 0,
					MinutesBeforehand = 0,
				};
			}
		}

		}
	}
}
