// <auto-generated> - Template:XamSample, Version:1.0, Id:9131a0a2-7ceb-4f4c-b8a9-6740ac19f66c
using System;
using CodeGenHero.BingoBuzz.DTO.BB;

namespace CodeGenHero.BingoBuzz.DTO.BB
{
	public static class DemoUser
		{
		public static System.Guid SampleUserId00 = Guid.Parse("f191975a-56c5-46ee-9b10-6e593757c9b0");
		public static System.Guid SampleUserId01 = Guid.Parse("0d33572a-e157-46df-bc1b-063fc6418622");

		public static User SampleUser00
		{
			get
			{
				return new User()
				{
					UserId = SampleUserId00,
					CompanyId = Guid.Parse("a54392e0-d499-4c1f-b15f-2e3b6b67079e"),
					Email = "SampleEmail",
					FirstName = "SampleFirstName",
					LastName = "SampleLastName",
					CreatedDate = DateTime.Now,
					CreatedUserId = Guid.Parse("f4d934a2-de2d-4220-ad35-53d77a25aa64"),
					UpdatedDate = DateTime.Now,
					UpdatedUserId = Guid.Parse("5bfb3ee1-1bf7-471e-bf5f-6e88d4d3394d"),
					IsDeleted = false,
				};
			}
		}
		public static User SampleUser01
		{
			get
			{
				return new User()
				{
					UserId = SampleUserId01,
					CompanyId = Guid.Parse("99a1db74-9400-4c41-9d48-3018a3a8232b"),
					Email = "SampleEmail",
					FirstName = "SampleFirstName",
					LastName = "SampleLastName",
					CreatedDate = DateTime.Now,
					CreatedUserId = Guid.Parse("dc83a319-942c-4b2a-a56e-d1f767fa340a"),
					UpdatedDate = DateTime.Now,
					UpdatedUserId = Guid.Parse("70eb4977-3827-4730-8d97-1bb1e5bbfbd3"),
					IsDeleted = false,
				};
			}
		}

		}
	}
}
