// <auto-generated> - Template:ModelsBackedByDtoInterface, Version:1.0, Id:4d03f2c7-de27-4aae-a267-cad747c9606a
using System;
using System.Collections.Generic;

namespace CodeGenHero.BingoBuzz.Model.BB.Interface
{
	public partial interface IBingoInstance
	{
		System.Guid BingoInstanceId { get; }
		int BingoInstanceStatusTypeId { get; }
		System.DateTime CreatedDate { get; }
		System.Guid CreatedUserId { get; }
		bool IncludeFreeSquareIndicator { get; }
		bool IsDeleted { get; }
		System.Guid? MeetingId { get; }
		int NumberOfColumns { get; }
		int NumberOfRows { get; }
		System.DateTime UpdatedDate { get; }
		System.Guid UpdatedUserId { get; }

		IMeeting Meeting { get; }
		IUser CreatedUser { get; }
		IUser UpdatedUser { get; }
		List<IBingoInstanceContent> BingoInstanceContents { get; }
		List<IBingoInstanceEvent> BingoInstanceEvents { get; }


	}
}
