// <auto-generated> - Template:ModelsBackedByDtoInterface, Version:1.0, Id:4d03f2c7-de27-4aae-a267-cad747c9606a
using System;
using System.Collections.Generic;

namespace CodeGenHero.BingoBuzz.Model.BB.Interface
{
	public partial interface IMeetingSchedule
	{
		System.DateTime CreatedDate { get; }
		System.Guid CreatedUserId { get; }
		System.DateTime? EndDate { get; }
		bool IsDeleted { get; }
		System.Guid? MeetingId { get; }
		System.Guid MeetingScheduleId { get; }
		System.Guid? RecurrenceRuleId { get; }
		System.DateTime? StartDate { get; }
		System.DateTime UpdatedDate { get; }
		System.Guid UpdatedUserId { get; }

		IMeeting Meeting { get; }
		IRecurrenceRule RecurrenceRule { get; }
		IUser CreatedUser { get; }
		IUser UpdatedUser { get; }


	}
}
