// <auto-generated>
namespace MSC.BingoBuzz.DTO.BB
{
	public partial class BingoInstanceContent
	{
		public BingoInstanceContent()
		{
			BingoInstanceEvents = new System.Collections.Generic.List<BingoInstanceEvent>();

			InitializePartial();
		}

		public System.Guid BingoInstanceContentId { get; set; } // Primary key
		public System.Guid BingoInstanceId { get; set; }
		public int Col { get; set; }
		public int Row { get; set; }
		public bool FreeSquareIndicator { get; set; }
		public System.DateTime CreatedDate { get; set; }
		public System.Guid CreatedUserId { get; set; }
		public System.DateTime UpdatedDate { get; set; }
		public System.Guid UpdatedUserId { get; set; }
		public bool IsDeleted { get; set; }
		public virtual System.Collections.Generic.ICollection<BingoInstanceEvent> BingoInstanceEvents { get; set; } // Many to many mapping
		public virtual BingoInstance BingoInstance { get; set; } 
		public virtual User CreatedUser { get; set; } 
		public virtual User UpdatedUser { get; set; } 


		partial void InitializePartial();

	}
}
