// <auto-generated>
namespace MSC.BingoBuzz.DTO.BB
{
	public partial class BingoInstanceEventType
	{
		public BingoInstanceEventType()
		{
			BingoInstanceEvents = new System.Collections.Generic.List<BingoInstanceEvent>();

			InitializePartial();
		}

		public int BingoInstanceEventTypeId { get; set; } // Primary key
		public string Name { get; set; }
		public virtual System.Collections.Generic.ICollection<BingoInstanceEvent> BingoInstanceEvents { get; set; } // Many to many mapping


		partial void InitializePartial();

	}
}
