// <auto-generated>
namespace MSC.BingoBuzz.DTO.BB
{
	public partial class FrequencyType
	{
		public FrequencyType()
		{
			RecurrenceRules = new System.Collections.Generic.List<RecurrenceRule>();

			InitializePartial();
		}

		public int FrequencyTypeId { get; set; } // Primary key
		public string Name { get; set; }
		public virtual System.Collections.Generic.ICollection<RecurrenceRule> RecurrenceRules { get; set; } // Many to many mapping


		partial void InitializePartial();

	}
}
