// <auto-generated>
namespace MSC.BingoBuzz.DTO.BB
{
	public partial class NotificationRule
	{
		public NotificationRule()
		{
			MeetingAttendees = new System.Collections.Generic.List<MeetingAttendee>();

			InitializePartial();
		}

		public System.Guid NotificationRuleId { get; set; } // Primary key
		public int NotificationMethodTypeId { get; set; }
		public int MinutesBeforehand { get; set; }
		public virtual System.Collections.Generic.ICollection<MeetingAttendee> MeetingAttendees { get; set; } // Many to many mapping
		public virtual NotificationMethodType NotificationMethodType { get; set; } 


		partial void InitializePartial();

	}
}
