// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace MSC.BingoBuzz.Repository.Entities.BB
{

    // BingoContent
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class BingoContent
    {
        public System.Guid BingoContentId { get; set; } // BingoContentId (Primary key)
        public string Content { get; set; } // Content (Primary key) (length: 250)
        public bool FreeSquareIndicator { get; set; } // FreeSquareIndicator (Primary key)
        public int NumberOfUpvotes { get; set; } // NumberOfUpvotes (Primary key)
        public int NumberOfDownvotes { get; set; } // NumberOfDownvotes (Primary key)
        public System.DateTime CreatedDate { get; set; } // CreatedDate (Primary key)
        public System.Guid CreatedUserId { get; set; } // CreatedUserId (Primary key)
        public System.DateTime UpdatedDate { get; set; } // UpdatedDate (Primary key)
        public System.Guid UpdatedUserId { get; set; } // UpdatedUserId (Primary key)
        public bool IsDeleted { get; set; } // IsDeleted (Primary key)

        // Foreign keys

        /// <summary>
        /// Parent User pointed by [BingoContent].([CreatedUserId]) (FK_BingoContent_User_CreatedUserId)
        /// </summary>
        public virtual User CreatedUser { get; set; } // FK_BingoContent_User_CreatedUserId

        /// <summary>
        /// Parent User pointed by [BingoContent].([UpdatedUserId]) (FK_BingoContent_User_UpdatedUserId)
        /// </summary>
        public virtual User UpdatedUser { get; set; } // FK_BingoContent_User_UpdatedUserId

        public BingoContent()
        {
            BingoContentId = System.Guid.NewGuid();
            FreeSquareIndicator = false;
            NumberOfUpvotes = 0;
            NumberOfDownvotes = 0;
            IsDeleted = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
