// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace MSC.BingoBuzz.Repository.Entities.BB
{

    // BingoInstanceContent
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class BingoInstanceContentConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<BingoInstanceContent>
    {
        public BingoInstanceContentConfiguration()
            : this("dbo")
        {
        }

        public BingoInstanceContentConfiguration(string schema)
        {
            ToTable("BingoInstanceContent", schema);
            HasKey(x => x.BingoInstanceContentId);

            Property(x => x.BingoInstanceContentId).HasColumnName(@"BingoInstanceContentId").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.BingoContentId).HasColumnName(@"BingoContentId").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.BingoInstanceId).HasColumnName(@"BingoInstanceId").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.Col).HasColumnName(@"Col").HasColumnType("int").IsRequired();
            Property(x => x.Row).HasColumnName(@"Row").HasColumnType("int").IsRequired();
            Property(x => x.FreeSquareIndicator).HasColumnName(@"FreeSquareIndicator").HasColumnType("bit").IsRequired();
            Property(x => x.CreatedDate).HasColumnName(@"CreatedDate").HasColumnType("datetime2").IsRequired();
            Property(x => x.CreatedUserId).HasColumnName(@"CreatedUserId").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.UpdatedDate).HasColumnName(@"UpdatedDate").HasColumnType("datetime2").IsRequired();
            Property(x => x.UpdatedUserId).HasColumnName(@"UpdatedUserId").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.IsDeleted).HasColumnName(@"IsDeleted").HasColumnType("bit").IsRequired();

            // Foreign keys
            HasRequired(a => a.BingoContent).WithMany(b => b.BingoInstanceContents).HasForeignKey(c => c.BingoContentId).WillCascadeOnDelete(false); // FK_BingoInstanceContent_BingoContent
            HasRequired(a => a.BingoInstance).WithMany(b => b.BingoInstanceContents).HasForeignKey(c => c.BingoInstanceId).WillCascadeOnDelete(false); // FK_BingoInstanceContent_BingoInstance
            HasRequired(a => a.CreatedUser).WithMany(b => b.BingoInstanceContents_CreatedUserId).HasForeignKey(c => c.CreatedUserId).WillCascadeOnDelete(false); // FK_BingoInstanceContent_User_Created
            HasRequired(a => a.UpdatedUser).WithMany(b => b.BingoInstanceContents_UpdatedUserId).HasForeignKey(c => c.UpdatedUserId).WillCascadeOnDelete(false); // FK_BingoInstanceContent_User_Updated
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
