// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CodeGenHero.BingoBuzz.Repository.Entities.BB
{

    // NotificationMethodType
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class NotificationMethodType
    {
        public int NotificationMethodTypeId { get; set; } // NotificationMethodTypeId (Primary key)
        public string Name { get; set; } // Name (length: 250)

        // Reverse navigation

        /// <summary>
        /// Child NotificationRules where [NotificationRule].[NotificationMethodTypeId] point to this entity (FK_NotificationRule_NotificationMethodType)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<NotificationRule> NotificationRules { get; set; } // NotificationRule.FK_NotificationRule_NotificationMethodType

        public NotificationMethodType()
        {
            NotificationRules = new System.Collections.Generic.List<NotificationRule>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
