// <auto-generated> - Template:SqliteModelData, Version:1.1, Id:c5caad15-b3be-4443-87d8-7cabde59f7b0
using CodeGenHero.Xam.Sqlite;
using SQLite;

namespace CodeGenHero.BingoBuzz.Xam.ModelData.BB
{
	[Table("BingoInstanceContent")]
	public partial class BingoInstanceContent : BaseAuditEdit
	{
		public System.Guid BingoContentId { get; set; }

		[PrimaryKey]
		public System.Guid BingoInstanceContentId { get; set; }

		public int BingoInstanceContentStatusTypeId { get; set; }
		public System.Guid BingoInstanceId { get; set; }
		public int Col { get; set; }
		public bool FreeSquareIndicator { get; set; }
		public int Row { get; set; }
		public System.Guid UserId { get; set; }
	}
}
