// <auto-generated> - Template:SqliteModelData, Version:1.1, Id:c5caad15-b3be-4443-87d8-7cabde59f7b0
using CodeGenHero.Xam.Sqlite;
using SQLite;

namespace CodeGenHero.BingoBuzz.Xam.ModelData.BB
{
	[Table("BingoInstance")]
	public partial class BingoInstance : BaseAuditEdit
	{

		[PrimaryKey]
		public System.Guid BingoInstanceId { get; set; }

		public int BingoInstanceStatusTypeId { get; set; }
		public bool IncludeFreeSquareIndicator { get; set; }
		public System.Guid? MeetingId { get; set; }
		public int NumberOfColumns { get; set; }
		public int NumberOfRows { get; set; }
	}
}
