// <auto-generated> - Template:SqliteModelData, Version:1.1, Id:c5caad15-b3be-4443-87d8-7cabde59f7b0
using CodeGenHero.Xam.Sqlite;
using SQLite;

namespace CodeGenHero.BingoBuzz.Xam.ModelData.BB
{
	[Table("MeetingAttendee")]
	public partial class MeetingAttendee : BaseAuditEdit
	{

		[PrimaryKey]
		public System.Guid MeetingAttendeeId { get; set; }

		public System.Guid MeetingId { get; set; }
		public System.Guid? NotificationRuleId { get; set; }
		public System.Guid UserId { get; set; }
	}
}
