// <auto-generated> - Template:SqliteModelData, Version:1.1, Id:c5caad15-b3be-4443-87d8-7cabde59f7b0
using SQLite;

namespace CodeGenHero.BingoBuzz.Xam.ModelData.BB
{
	[Table("NotificationMethodType")]
	public partial class NotificationMethodType
	{
		public string Name { get; set; }

		[PrimaryKey]
		public int NotificationMethodTypeId { get; set; }

	}
}
