// <auto-generated>
using GalaSoft.MvvmLight;
using CodeGenHero.EAMVCXamPOCO.Xam.ModelObj;

namespace MSC.BingoBuzz.Xam.ModelObj.BB
{
	public partial class BingoContent : BaseAuditEdit
	{
		public BingoContent()
		{
			BingoInstanceContents = new System.Collections.Generic.List<BingoInstanceContent>();

			InitializePartial();
		}

		private System.Guid _bingoContentId;
		private string _content;
		private bool _freeSquareIndicator;
		private int _numberOfDownvotes;
		private int _numberOfUpvotes;


		public System.Guid BingoContentId
		{
			get { return _bingoContentId; }
			set
			{
				Set<System.Guid>(() => BingoContentId, ref _bingoContentId, value);
				RunCustomLogicSetBingoContentId(value);
			}
		}

		public string Content
		{
			get { return _content; }
			set
			{
				Set<string>(() => Content, ref _content, value);
				RunCustomLogicSetContent(value);
			}
		}

		public bool FreeSquareIndicator
		{
			get { return _freeSquareIndicator; }
			set
			{
				Set<bool>(() => FreeSquareIndicator, ref _freeSquareIndicator, value);
				RunCustomLogicSetFreeSquareIndicator(value);
			}
		}

		public int NumberOfDownvotes
		{
			get { return _numberOfDownvotes; }
			set
			{
				Set<int>(() => NumberOfDownvotes, ref _numberOfDownvotes, value);
				RunCustomLogicSetNumberOfDownvotes(value);
			}
		}

		public int NumberOfUpvotes
		{
			get { return _numberOfUpvotes; }
			set
			{
				Set<int>(() => NumberOfUpvotes, ref _numberOfUpvotes, value);
				RunCustomLogicSetNumberOfUpvotes(value);
			}
		}

		public virtual System.Collections.Generic.ICollection<BingoInstanceContent> BingoInstanceContents { get; set; } // Many to many mapping
		public virtual User CreatedUser { get; set; } 
		public virtual User UpdatedUser { get; set; } 


		partial void InitializePartial();

		#region RunCustomLogicSet

		partial void RunCustomLogicSetBingoContentId(System.Guid value);
		partial void RunCustomLogicSetContent(string value);
		partial void RunCustomLogicSetFreeSquareIndicator(bool value);
		partial void RunCustomLogicSetNumberOfDownvotes(int value);
		partial void RunCustomLogicSetNumberOfUpvotes(int value);

		#endregion RunCustomLogicSet

	}
}
