// <auto-generated> - Template:MvvmLightModelObject, Version:1.0, Id:4d03f2c7-de26-4aee-a267-cad747c9606a
using GalaSoft.MvvmLight;

namespace CodeGenHero.BingoBuzz.Xam.ModelObj.BB
{
	public partial class BingoInstanceStatusType : ObservableObject
	{
		public BingoInstanceStatusType()
		{
			InitializePartial();
		}

		private int _bingoInstanceStatusTypeId;
		private string _name;


		public int BingoInstanceStatusTypeId
		{
			get { return _bingoInstanceStatusTypeId; }
			set
			{
				Set<int>(() => BingoInstanceStatusTypeId, ref _bingoInstanceStatusTypeId, value);
				RunCustomLogicSetBingoInstanceStatusTypeId(value);
			}
		}

		public string Name
		{
			get { return _name; }
			set
			{
				Set<string>(() => Name, ref _name, value);
				RunCustomLogicSetName(value);
			}
		}



		partial void InitializePartial();

		#region RunCustomLogicSet

		partial void RunCustomLogicSetBingoInstanceStatusTypeId(int value);
		partial void RunCustomLogicSetName(string value);

		#endregion RunCustomLogicSet

	}
}
