// <auto-generated>
using GalaSoft.MvvmLight;
using MSC.BingoBuzz.Xam.ModelObj;

namespace MSC.BingoBuzz.Xam.ModelObj.BB
{
	public partial class NotificationMethodType : ObservableObject
	{
		public NotificationMethodType()
		{
			NotificationRules = new System.Collections.Generic.List<NotificationRule>();

			InitializePartial();
		}

		private string _name;
		private int _notificationMethodTypeId;


		public string Name
		{
			get { return _name; }
			set
			{
				Set<string>(() => Name, ref _name, value);
				RunCustomLogicSetName(value);
			}
		}

		public int NotificationMethodTypeId
		{
			get { return _notificationMethodTypeId; }
			set
			{
				Set<int>(() => NotificationMethodTypeId, ref _notificationMethodTypeId, value);
				RunCustomLogicSetNotificationMethodTypeId(value);
			}
		}

		public virtual System.Collections.Generic.ICollection<NotificationRule> NotificationRules { get; set; } // Many to many mapping


		partial void InitializePartial();

		#region RunCustomLogicSet

		partial void RunCustomLogicSetName(string value);
		partial void RunCustomLogicSetNotificationMethodTypeId(int value);

		#endregion RunCustomLogicSet

	}
}
