// <auto-generated> - Template:MvvmLightModelObject, Version:1.0, Id:c644a31c-7ebc-4383-bc7f-0ea7c5bf6ed4
using GalaSoft.MvvmLight;

namespace CodeGenHero.BingoBuzz.Xam.ModelObj.BB
{
	public partial class FrequencyType : ObservableObject
	{
		public FrequencyType()
		{
			RecurrenceRules = new System.Collections.Generic.List<RecurrenceRule>(); // Reverse Navigation

			InitializePartial();
		}

		private int _frequencyTypeId;
		private string _name;


		public int FrequencyTypeId
		{
			get { return _frequencyTypeId; }
			set
			{
				Set<int>(() => FrequencyTypeId, ref _frequencyTypeId, value);
				RunCustomLogicSetFrequencyTypeId(value);
			}
		}

		public string Name
		{
			get { return _name; }
			set
			{
				Set<string>(() => Name, ref _name, value);
				RunCustomLogicSetName(value);
			}
		}

		public virtual System.Collections.Generic.IList<RecurrenceRule> RecurrenceRules { get; set; } // Many to many mapping


		partial void InitializePartial();

		#region RunCustomLogicSet

		partial void RunCustomLogicSetFrequencyTypeId(int value);
		partial void RunCustomLogicSetName(string value);

		#endregion RunCustomLogicSet

	}
}
