// <auto-generated> - Template:MvvmLightModelObject, Version:1.0, Id:c644a31c-7ebc-4383-bc7f-0ea7c5bf6ed4
using GalaSoft.MvvmLight;
using CodeGenHero.Xam.MvvmLight;

namespace CodeGenHero.BingoBuzz.Xam.ModelObj.BB
{
	public partial class MeetingAttendee : BaseAuditEdit
	{
		public MeetingAttendee()
		{
			InitializePartial();
		}

		private System.Guid _meetingAttendeeId;
		private System.Guid _meetingId;
		private System.Guid? _notificationRuleId;
		private System.Guid _userId;


		public System.Guid MeetingAttendeeId
		{
			get { return _meetingAttendeeId; }
			set
			{
				Set<System.Guid>(() => MeetingAttendeeId, ref _meetingAttendeeId, value);
				RunCustomLogicSetMeetingAttendeeId(value);
			}
		}

		public System.Guid MeetingId
		{
			get { return _meetingId; }
			set
			{
				Set<System.Guid>(() => MeetingId, ref _meetingId, value);
				RunCustomLogicSetMeetingId(value);
			}
		}

		public System.Guid? NotificationRuleId
		{
			get { return _notificationRuleId; }
			set
			{
				Set<System.Guid?>(() => NotificationRuleId, ref _notificationRuleId, value);
				RunCustomLogicSetNotificationRuleId(value);
			}
		}

		public System.Guid UserId
		{
			get { return _userId; }
			set
			{
				Set<System.Guid>(() => UserId, ref _userId, value);
				RunCustomLogicSetUserId(value);
			}
		}

		public virtual Meeting Meeting { get; set; } 
		public virtual NotificationRule NotificationRule { get; set; } 
		public virtual User CreatedUser { get; set; } 
		public virtual User UpdatedUser { get; set; } 
		public virtual User User_UserId { get; set; } 


		partial void InitializePartial();

		#region RunCustomLogicSet

		partial void RunCustomLogicSetMeetingAttendeeId(System.Guid value);
		partial void RunCustomLogicSetMeetingId(System.Guid value);
		partial void RunCustomLogicSetNotificationRuleId(System.Guid? value);
		partial void RunCustomLogicSetUserId(System.Guid value);

		#endregion RunCustomLogicSet

	}
}
