// <auto-generated> - Template:MvvmLightModelObject, Version:1.1, Id:c644a31c-7ebc-4383-bc7f-0ea7c5bf6ed4
using GalaSoft.MvvmLight;
using CodeGenHero.Xam.MvvmLight;

namespace CodeGenHero.BingoBuzz.Xam.ModelObj.BB
{
	public partial class Meeting : BaseAuditEdit
	{
		public Meeting()
		{
			BingoInstances = new System.Collections.Generic.List<BingoInstance>(); // Reverse Navigation
			MeetingAttendees = new System.Collections.Generic.List<MeetingAttendee>(); // Reverse Navigation
			MeetingSchedules = new System.Collections.Generic.List<MeetingSchedule>(); // Reverse Navigation

			InitializePartial();
		}

		private System.Guid? _companyId;
		private System.Guid _meetingId;
		private string _name;


		public System.Guid? CompanyId
		{
			get { return _companyId; }
			set
			{
				Set<System.Guid?>(() => CompanyId, ref _companyId, value);
				RunCustomLogicSetCompanyId(value);
			}
		}

		public System.Guid MeetingId
		{
			get { return _meetingId; }
			set
			{
				Set<System.Guid>(() => MeetingId, ref _meetingId, value);
				RunCustomLogicSetMeetingId(value);
			}
		}

		public string Name
		{
			get { return _name; }
			set
			{
				Set<string>(() => Name, ref _name, value);
				RunCustomLogicSetName(value);
			}
		}

		public virtual System.Collections.Generic.IList<BingoInstance> BingoInstances { get; set; } // Many to many mapping
		public virtual System.Collections.Generic.IList<MeetingAttendee> MeetingAttendees { get; set; } // Many to many mapping
		public virtual System.Collections.Generic.IList<MeetingSchedule> MeetingSchedules { get; set; } // Many to many mapping
		public virtual Company Company { get; set; } 
		public virtual User CreatedUser { get; set; } 
		public virtual User UpdatedUser { get; set; } 


		partial void InitializePartial();

		#region RunCustomLogicSet

		partial void RunCustomLogicSetCompanyId(System.Guid? value);
		partial void RunCustomLogicSetMeetingId(System.Guid value);
		partial void RunCustomLogicSetName(string value);

		#endregion RunCustomLogicSet

	}
}
