// <auto-generated> - Template:MvvmLightModelObject, Version:1.0, Id:4d03f2c7-de26-4aee-a267-cad747c9606a
using GalaSoft.MvvmLight;

namespace CodeGenHero.BingoBuzz.Xam.ModelObj.BB
{
	public partial class NotificationMethodType : ObservableObject
	{
		public NotificationMethodType()
		{
			NotificationRules = new System.Collections.Generic.List<NotificationRule>(); // Reverse Navigation

			InitializePartial();
		}

		private string _name;
		private int _notificationMethodTypeId;


		public string Name
		{
			get { return _name; }
			set
			{
				Set<string>(() => Name, ref _name, value);
				RunCustomLogicSetName(value);
			}
		}

		public int NotificationMethodTypeId
		{
			get { return _notificationMethodTypeId; }
			set
			{
				Set<int>(() => NotificationMethodTypeId, ref _notificationMethodTypeId, value);
				RunCustomLogicSetNotificationMethodTypeId(value);
			}
		}

		public virtual System.Collections.Generic.IList<NotificationRule> NotificationRules { get; set; } // Many to many mapping


		partial void InitializePartial();

		#region RunCustomLogicSet

		partial void RunCustomLogicSetName(string value);
		partial void RunCustomLogicSetNotificationMethodTypeId(int value);

		#endregion RunCustomLogicSet

	}
}
