// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CodeGenHero.BingoBuzz.Repository.Entities.BB
{

    // BingoInstanceContentStatusType
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class BingoInstanceContentStatusType
    {
        public int BingoInstanceContentStatusTypeId { get; set; } // BingoInstanceContentStatusTypeId (Primary key)
        public string Name { get; set; } // Name (length: 250)

        // Reverse navigation

        /// <summary>
        /// Child BingoInstanceContents where [BingoInstanceContent].[BingoInstanceContentStatusTypeId] point to this entity (FK_BingoInstanceContent_BingoInstanceContentStatusType)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<BingoInstanceContent> BingoInstanceContents { get; set; } // BingoInstanceContent.FK_BingoInstanceContent_BingoInstanceContentStatusType

        public BingoInstanceContentStatusType()
        {
            BingoInstanceContents = new System.Collections.Generic.List<BingoInstanceContent>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
