// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace CodeGenHero.BingoBuzz.Repository.Entities.BB
{

    // Company
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class Company
    {
        public System.Guid CompanyId { get; set; } // CompanyId (Primary key)
        public string Name { get; set; } // Name (length: 100)
        public string CodeName { get; set; } // CodeName (length: 50)
        public string Address1 { get; set; } // Address1 (length: 100)
        public string Address2 { get; set; } // Address2 (length: 100)
        public string City { get; set; } // City (length: 100)
        public string State { get; set; } // State (length: 50)
        public string Zip { get; set; } // Zip (length: 50)
        public string WebsiteUrl { get; set; } // WebsiteUrl (length: 100)
        public System.DateTime CreatedDate { get; set; } // CreatedDate
        public System.Guid CreatedUserId { get; set; } // CreatedUserId
        public System.DateTime UpdatedDate { get; set; } // UpdatedDate
        public System.Guid UpdatedUserId { get; set; } // UpdatedUserId
        public bool IsDeleted { get; set; } // IsDeleted

        // Reverse navigation

        /// <summary>
        /// Child Meetings where [Meeting].[CompanyId] point to this entity (FK_Meeting_Company)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Meeting> Meetings { get; set; } // Meeting.FK_Meeting_Company

        // Foreign keys

        /// <summary>
        /// Parent User pointed by [Company].([CreatedUserId]) (FK_Company_User_Created)
        /// </summary>
        public virtual User CreatedUser { get; set; } // FK_Company_User_Created

        /// <summary>
        /// Parent User pointed by [Company].([UpdatedUserId]) (FK_Company_User_Updated)
        /// </summary>
        public virtual User UpdatedUser { get; set; } // FK_Company_User_Updated

        public Company()
        {
            CompanyId = System.Guid.NewGuid();
            IsDeleted = false;
            Meetings = new System.Collections.Generic.List<Meeting>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
