// <auto-generated> - Template:ModelsBackedByDto, Version:1.1, Id:f1539c0d-024f-4b1f-b346-132cdd9dd31f
using CodeGenHero.Logging;
using CodeGenHero.DataService;
using System;
using System.Collections.Generic;
using System.Linq;
using CodeGenHero.BingoBuzz.API.Client.Interface;
using CodeGenHero.BingoBuzz.Model.BB.Interface;
using xDTO = CodeGenHero.BingoBuzz.DTO.BB;

namespace CodeGenHero.BingoBuzz.Model.BB
{

	public class LoadRequestBingoInstanceContentStatusType : EventArgs
	{
		public LoadRequestBingoInstanceContentStatusType(string propertyNameRequestingLoad)
		{
			PropertyNameRequestingLoad = propertyNameRequestingLoad;
		}

		public string PropertyNameRequestingLoad { get; set; }
	}


	public partial class BingoInstanceContentStatusType : BaseModel<IWebApiDataServiceBB>, IBingoInstanceContentStatusType
	{
		public event EventHandler<LoadRequestBingoInstanceContentStatusType> OnLazyLoadRequest = delegate { }; // Empty delegate. Thus we are sure that value is always != null because no one outside of the class can change it.
		private xDTO.BingoInstanceContentStatusType _dto = null;

		public BingoInstanceContentStatusType(ILoggingService log, IDataService<IWebApiDataServiceBB> dataService) : base(log, dataService)
		{
			_dto = new xDTO.BingoInstanceContentStatusType();
			OnLazyLoadRequest += HandleLazyLoadRequest;
		}

		public BingoInstanceContentStatusType(ILoggingService log, IDataService<IWebApiDataServiceBB> dataService, xDTO.BingoInstanceContentStatusType dto) : this(log, dataService)
		{
			_dto = dto;
		}


		public virtual int BingoInstanceContentStatusTypeId { get { return _dto.BingoInstanceContentStatusTypeId; } }
		public virtual string Name { get { return _dto.Name; } }

		private List<IBingoInstanceContent> _bingoInstanceContents = null; // Reverse Navigation


		public virtual List<IBingoInstanceContent> BingoInstanceContents
		{
			get
			{
				if (_bingoInstanceContents == null)
				{
					OnLazyLoadRequest(this, new LoadRequestBingoInstanceContentStatusType(nameof(BingoInstanceContents)));
				}

				return _bingoInstanceContents;
			}
		}



	}
}
