// <auto-generated> - Template:ModelsBackedByDto, Version:1.0, Id:4d03f2c7-de26-4abe-a267-cad747c9606a
using CodeGenHero.Logging;
using CodeGenHero.DataService;
using System;
using System.Collections.Generic;
using System.Linq;
using CodeGenHero.BingoBuzz.API.Client.Interface;
using CodeGenHero.BingoBuzz.Model.BB.Interface;
using xDTO = CodeGenHero.BingoBuzz.DTO.BB;

namespace CodeGenHero.BingoBuzz.Model.BB
{

	public class LoadRequestUser : EventArgs
	{
		public LoadRequestUser(string propertyNameRequestingLoad)
		{
			PropertyNameRequestingLoad = propertyNameRequestingLoad;
		}

		public string PropertyNameRequestingLoad { get; set; }
	}


	public partial class User : BaseModel<IWebApiDataServiceBB>, IUser
	{
		public event EventHandler<LoadRequestUser> OnLazyLoadRequest = delegate { }; // Empty delegate. Thus we are sure that value is always != null because no one outside of the class can change it.
		private xDTO.User _dto = null;

		public User(ILoggingService log, IDataService<IWebApiDataServiceBB> dataService) : base(log, dataService)
		{
			_dto = new xDTO.User();
			OnLazyLoadRequest += HandleLazyLoadRequestAsync;
		}

		public User(ILoggingService log, IDataService<IWebApiDataServiceBB> dataService, xDTO.User dto) : this(log, dataService)
		{
			_dto = dto;
		}


		public virtual System.Guid CompanyId { get { return _dto.CompanyId; } }
		public virtual System.DateTime CreatedDate { get { return _dto.CreatedDate; } }
		public virtual System.Guid CreatedUserId { get { return _dto.CreatedUserId; } }
		public virtual string Email { get { return _dto.Email; } }
		public virtual string FirstName { get { return _dto.FirstName; } }
		public virtual bool IsDeleted { get { return _dto.IsDeleted; } }
		public virtual string LastName { get { return _dto.LastName; } }
		public virtual System.DateTime UpdatedDate { get { return _dto.UpdatedDate; } }
		public virtual System.Guid UpdatedUserId { get { return _dto.UpdatedUserId; } }
		public virtual System.Guid UserId { get { return _dto.UserId; } }

		private IUser _user_CreatedUserId = null; // Foreign Key
		private IUser _user_UpdatedUserId = null; // Foreign Key
		private List<IBingoContent> _bingoContents_UpdatedUserId = null; // Reverse Navigation
		private List<IBingoContent> _createdUser = null; // Reverse Navigation
		private List<IBingoInstance> _bingoInstances_CreatedUserId = null; // Reverse Navigation
		private List<IBingoInstance> _bingoInstances_UpdatedUserId = null; // Reverse Navigation
		private List<IBingoInstanceContent> _bingoInstanceContents_CreatedUserId = null; // Reverse Navigation
		private List<IBingoInstanceContent> _bingoInstanceContents_UpdatedUserId = null; // Reverse Navigation
		private List<IBingoInstanceContent> _bingoInstanceContents_UserId = null; // Reverse Navigation
		private List<IBingoInstanceEvent> _bingoInstanceEvents_CreatedUserId = null; // Reverse Navigation
		private List<IBingoInstanceEvent> _bingoInstanceEvents_UpdatedUserId = null; // Reverse Navigation
		private List<ICompany> _companies_CreatedUserId = null; // Reverse Navigation
		private List<ICompany> _companies_UpdatedUserId = null; // Reverse Navigation
		private List<IMeeting> _meetings_CreatedUserId = null; // Reverse Navigation
		private List<IMeeting> _meetings_UpdatedUserId = null; // Reverse Navigation
		private List<IMeetingAttendee> _meetingAttendees_CreatedUserId = null; // Reverse Navigation
		private List<IMeetingAttendee> _meetingAttendees_UpdatedUserId = null; // Reverse Navigation
		private List<IMeetingAttendee> _meetingAttendees_UserId = null; // Reverse Navigation
		private List<IMeetingSchedule> _meetingSchedules_CreatedUserId = null; // Reverse Navigation
		private List<IMeetingSchedule> _meetingSchedules_UpdatedUserId = null; // Reverse Navigation
		private List<IUser> _users_CreatedUserId = null; // Reverse Navigation
		private List<IUser> _users_UpdatedUserId = null; // Reverse Navigation


		public virtual IUser User_CreatedUserId
		{
			get
			{
				if (_user_CreatedUserId == null)
				{
					OnLazyLoadRequest(this, new LoadRequestUser(nameof(User_CreatedUserId)));
				}

				return _user_CreatedUserId;
			}
		}

		public virtual IUser User_UpdatedUserId
		{
			get
			{
				if (_user_UpdatedUserId == null)
				{
					OnLazyLoadRequest(this, new LoadRequestUser(nameof(User_UpdatedUserId)));
				}

				return _user_UpdatedUserId;
			}
		}

		public virtual List<IBingoContent> BingoContents_UpdatedUserId
		{
			get
			{
				if (_bingoContents_UpdatedUserId == null)
				{
					OnLazyLoadRequest(this, new LoadRequestUser(nameof(BingoContents_UpdatedUserId)));
				}

				return _bingoContents_UpdatedUserId;
			}
		}

		public virtual List<IBingoContent> CreatedUser
		{
			get
			{
				if (_createdUser == null)
				{
					OnLazyLoadRequest(this, new LoadRequestUser(nameof(CreatedUser)));
				}

				return _createdUser;
			}
		}

		public virtual List<IBingoInstance> BingoInstances_CreatedUserId
		{
			get
			{
				if (_bingoInstances_CreatedUserId == null)
				{
					OnLazyLoadRequest(this, new LoadRequestUser(nameof(BingoInstances_CreatedUserId)));
				}

				return _bingoInstances_CreatedUserId;
			}
		}

		public virtual List<IBingoInstance> BingoInstances_UpdatedUserId
		{
			get
			{
				if (_bingoInstances_UpdatedUserId == null)
				{
					OnLazyLoadRequest(this, new LoadRequestUser(nameof(BingoInstances_UpdatedUserId)));
				}

				return _bingoInstances_UpdatedUserId;
			}
		}

		public virtual List<IBingoInstanceContent> BingoInstanceContents_CreatedUserId
		{
			get
			{
				if (_bingoInstanceContents_CreatedUserId == null)
				{
					OnLazyLoadRequest(this, new LoadRequestUser(nameof(BingoInstanceContents_CreatedUserId)));
				}

				return _bingoInstanceContents_CreatedUserId;
			}
		}

		public virtual List<IBingoInstanceContent> BingoInstanceContents_UpdatedUserId
		{
			get
			{
				if (_bingoInstanceContents_UpdatedUserId == null)
				{
					OnLazyLoadRequest(this, new LoadRequestUser(nameof(BingoInstanceContents_UpdatedUserId)));
				}

				return _bingoInstanceContents_UpdatedUserId;
			}
		}

		public virtual List<IBingoInstanceContent> BingoInstanceContents_UserId
		{
			get
			{
				if (_bingoInstanceContents_UserId == null)
				{
					OnLazyLoadRequest(this, new LoadRequestUser(nameof(BingoInstanceContents_UserId)));
				}

				return _bingoInstanceContents_UserId;
			}
		}

		public virtual List<IBingoInstanceEvent> BingoInstanceEvents_CreatedUserId
		{
			get
			{
				if (_bingoInstanceEvents_CreatedUserId == null)
				{
					OnLazyLoadRequest(this, new LoadRequestUser(nameof(BingoInstanceEvents_CreatedUserId)));
				}

				return _bingoInstanceEvents_CreatedUserId;
			}
		}

		public virtual List<IBingoInstanceEvent> BingoInstanceEvents_UpdatedUserId
		{
			get
			{
				if (_bingoInstanceEvents_UpdatedUserId == null)
				{
					OnLazyLoadRequest(this, new LoadRequestUser(nameof(BingoInstanceEvents_UpdatedUserId)));
				}

				return _bingoInstanceEvents_UpdatedUserId;
			}
		}

		public virtual List<ICompany> Companies_CreatedUserId
		{
			get
			{
				if (_companies_CreatedUserId == null)
				{
					OnLazyLoadRequest(this, new LoadRequestUser(nameof(Companies_CreatedUserId)));
				}

				return _companies_CreatedUserId;
			}
		}

		public virtual List<ICompany> Companies_UpdatedUserId
		{
			get
			{
				if (_companies_UpdatedUserId == null)
				{
					OnLazyLoadRequest(this, new LoadRequestUser(nameof(Companies_UpdatedUserId)));
				}

				return _companies_UpdatedUserId;
			}
		}

		public virtual List<IMeeting> Meetings_CreatedUserId
		{
			get
			{
				if (_meetings_CreatedUserId == null)
				{
					OnLazyLoadRequest(this, new LoadRequestUser(nameof(Meetings_CreatedUserId)));
				}

				return _meetings_CreatedUserId;
			}
		}

		public virtual List<IMeeting> Meetings_UpdatedUserId
		{
			get
			{
				if (_meetings_UpdatedUserId == null)
				{
					OnLazyLoadRequest(this, new LoadRequestUser(nameof(Meetings_UpdatedUserId)));
				}

				return _meetings_UpdatedUserId;
			}
		}

		public virtual List<IMeetingAttendee> MeetingAttendees_CreatedUserId
		{
			get
			{
				if (_meetingAttendees_CreatedUserId == null)
				{
					OnLazyLoadRequest(this, new LoadRequestUser(nameof(MeetingAttendees_CreatedUserId)));
				}

				return _meetingAttendees_CreatedUserId;
			}
		}

		public virtual List<IMeetingAttendee> MeetingAttendees_UpdatedUserId
		{
			get
			{
				if (_meetingAttendees_UpdatedUserId == null)
				{
					OnLazyLoadRequest(this, new LoadRequestUser(nameof(MeetingAttendees_UpdatedUserId)));
				}

				return _meetingAttendees_UpdatedUserId;
			}
		}

		public virtual List<IMeetingAttendee> MeetingAttendees_UserId
		{
			get
			{
				if (_meetingAttendees_UserId == null)
				{
					OnLazyLoadRequest(this, new LoadRequestUser(nameof(MeetingAttendees_UserId)));
				}

				return _meetingAttendees_UserId;
			}
		}

		public virtual List<IMeetingSchedule> MeetingSchedules_CreatedUserId
		{
			get
			{
				if (_meetingSchedules_CreatedUserId == null)
				{
					OnLazyLoadRequest(this, new LoadRequestUser(nameof(MeetingSchedules_CreatedUserId)));
				}

				return _meetingSchedules_CreatedUserId;
			}
		}

		public virtual List<IMeetingSchedule> MeetingSchedules_UpdatedUserId
		{
			get
			{
				if (_meetingSchedules_UpdatedUserId == null)
				{
					OnLazyLoadRequest(this, new LoadRequestUser(nameof(MeetingSchedules_UpdatedUserId)));
				}

				return _meetingSchedules_UpdatedUserId;
			}
		}

		public virtual List<IUser> Users_CreatedUserId
		{
			get
			{
				if (_users_CreatedUserId == null)
				{
					OnLazyLoadRequest(this, new LoadRequestUser(nameof(Users_CreatedUserId)));
				}

				return _users_CreatedUserId;
			}
		}

		public virtual List<IUser> Users_UpdatedUserId
		{
			get
			{
				if (_users_UpdatedUserId == null)
				{
					OnLazyLoadRequest(this, new LoadRequestUser(nameof(Users_UpdatedUserId)));
				}

				return _users_UpdatedUserId;
			}
		}



	}
}
