// <auto-generated>
using SQLite;
using MSC.BingoBuzz.Xam.ModelData;

namespace MSC.BingoBuzz.Xam.ModelData.BB
{
	[Table("BingoInstanceEventType")]
	public partial class BingoInstanceEventType
	{

		[PrimaryKey]
		public int BingoInstanceEventTypeId { get; set; }

		public string Name { get; set; }
	}
}
