// <auto-generated>
using CodeGenHero.EAMVCXamPOCO.Xam.ModelData;
using SQLite;

namespace MSC.BingoBuzz.Xam.ModelData.BB
{
	[Table("BingoInstanceContent")]
	public partial class BingoInstanceContent : BaseAuditEdit
	{
		public System.Guid BingoContentId { get; set; }

		[PrimaryKey]
		public System.Guid BingoInstanceContentId { get; set; }

		public System.Guid BingoInstanceId { get; set; }
		public int Col { get; set; }
		public bool FreeSquareIndicator { get; set; }
		public int Row { get; set; }
	}
}
