// <auto-generated>
using SQLite;
using CodeGenHero.EAMVCXamPOCO.Xam.ModelData;

namespace MSC.BingoBuzz.Xam.ModelData.BB
{
	[Table("Company")]
	public partial class Company : BaseAuditEdit
	{
		public string Address1 { get; set; }
		public string Address2 { get; set; }
		public string City { get; set; }
		public string CodeName { get; set; }

		[PrimaryKey]
		public System.Guid CompanyId { get; set; }

		public string Name { get; set; }
		public string State { get; set; }
		public string WebsiteUrl { get; set; }
		public string Zip { get; set; }
	}
}
