// <auto-generated>
using SQLite;

namespace MSC.BingoBuzz.Xam.ModelData.BB
{
	[Table("FrequencyType")]
	public partial class FrequencyType
	{

		[PrimaryKey]
		public int FrequencyTypeId { get; set; }

		public string Name { get; set; }
	}
}
