// <auto-generated>
using CodeGenHero.EAMVCXamPOCO.Xam.ModelData;
using SQLite;

namespace MSC.BingoBuzz.Xam.ModelData.BB
{
	[Table("Meeting")]
	public partial class Meeting : BaseAuditEdit
	{
		public System.Guid? CompanyId { get; set; }

		[PrimaryKey]
		public System.Guid MeetingId { get; set; }

		public string Name { get; set; }
	}
}
