// <auto-generated>
using SQLite;
using CodeGenHero.EAMVCXamPOCO.Xam.ModelData;

namespace MSC.BingoBuzz.Xam.ModelData.BB
{
	[Table("NotificationMethodType")]
	public partial class NotificationMethodType
	{
		public string Name { get; set; }

		[PrimaryKey]
		public int NotificationMethodTypeId { get; set; }

	}
}
