// <auto-generated> - Template:SqliteModelData, Version:1.0, Id:c5caad15-b3be-4443-87d8-7cabde59f7b0
using SQLite;

namespace CodeGenHero.BingoBuzz.Xam.ModelData.BB
{
	[Table("NotificationRule")]
	public partial class NotificationRule
	{
		public int MinutesBeforehand { get; set; }
		public int NotificationMethodTypeId { get; set; }

		[PrimaryKey]
		public System.Guid NotificationRuleId { get; set; }

	}
}
