// <auto-generated>
using SQLite;
using CodeGenHero.EAMVCXamPOCO.Xam.ModelData;


namespace MSC.BingoBuzz.Xam.ModelData.BB
{
	[Table("NotificationRule")]
	public partial class NotificationRule
	{
		public int MinutesBeforehand { get; set; }
		public int NotificationMethodTypeId { get; set; }

		[PrimaryKey]
		public System.Guid NotificationRuleId { get; set; }

	}
}
