// <auto-generated>
using SQLite;
using MSC.BingoBuzz.Xam.ModelData;

namespace MSC.BingoBuzz.Xam.ModelData.BB
{
	[Table("BingoContent")]
	public partial class BingoContent : BaseAuditEdit
	{

		[PrimaryKey]
		public System.Guid BingoContentId { get; set; }

		public string Content { get; set; }
		public bool FreeSquareIndicator { get; set; }
		public int NumberOfDownvotes { get; set; }
		public int NumberOfUpvotes { get; set; }
	}
}
