// <auto-generated>
using SQLite;
using MSC.BingoBuzz.Xam.ModelData;

namespace MSC.BingoBuzz.Xam.ModelData.BB
{
	[Table("MeetingSchedule")]
	public partial class MeetingSchedule : BaseAuditEdit
	{
		public System.DateTime? EndDate { get; set; }
		public System.Guid? MeetingId { get; set; }

		[PrimaryKey]
		public System.Guid MeetingScheduleId { get; set; }

		public System.Guid? RecurrenceRuleId { get; set; }
		public System.DateTime? StartDate { get; set; }
	}
}
