// <auto-generated>
using SQLite;
using MSC.BingoBuzz.Xam.ModelData;

namespace MSC.BingoBuzz.Xam.ModelData.BB
{
	[Table("MeetingAttendee")]
	public partial class MeetingAttendee : BaseAuditEdit
	{

		[PrimaryKey]
		public System.Guid MeetingAttendeeId { get; set; }

		public System.Guid MeetingId { get; set; }
		public System.Guid? NotificationRuleId { get; set; }
		public System.Guid UserId { get; set; }
	}
}
