// <auto-generated> - Template:ModelsBackedByDtoInterface, Version:1.1, Id:4d03f2c7-de27-4aae-a267-cad747c9606a
using System;
using System.Collections.Generic;

namespace CodeGenHero.BingoBuzz.Model.BB.Interface
{
	public partial interface IMeetingAttendee
	{
		System.DateTime CreatedDate { get; }
		System.Guid CreatedUserId { get; }
		bool IsDeleted { get; }
		System.Guid MeetingAttendeeId { get; }
		System.Guid MeetingId { get; }
		System.Guid? NotificationRuleId { get; }
		System.DateTime UpdatedDate { get; }
		System.Guid UpdatedUserId { get; }
		System.Guid UserId { get; }

		IMeeting Meeting { get; }
		INotificationRule NotificationRule { get; }
		IUser CreatedUser { get; }
		IUser UpdatedUser { get; }
		IUser User_UserId { get; }


	}
}
