// <auto-generated> - Template:ModelsBackedByDtoInterface, Version:1.1, Id:4d03f2c7-de27-4aae-a267-cad747c9606a
using System;
using System.Collections.Generic;

namespace CodeGenHero.BingoBuzz.Model.BB.Interface
{
	public partial interface IMeeting
	{
		System.Guid? CompanyId { get; }
		System.DateTime CreatedDate { get; }
		System.Guid CreatedUserId { get; }
		bool IsDeleted { get; }
		System.Guid MeetingId { get; }
		string Name { get; }
		System.DateTime UpdatedDate { get; }
		System.Guid UpdatedUserId { get; }

		ICompany Company { get; }
		IUser CreatedUser { get; }
		IUser UpdatedUser { get; }
		List<IBingoInstance> BingoInstances { get; }
		List<IMeetingAttendee> MeetingAttendees { get; }
		List<IMeetingSchedule> MeetingSchedules { get; }


	}
}
