// <auto-generated> - Template:ModelsBackedByDtoInterface, Version:1.0, Id:4d03f2c7-de27-4aae-a267-cad747c9606a
using System;
using System.Collections.Generic;

namespace CodeGenHero.BingoBuzz.Model.BB.Interface
{
	public partial interface IUser
	{
		System.Guid CompanyId { get; }
		System.DateTime CreatedDate { get; }
		System.Guid CreatedUserId { get; }
		string Email { get; }
		string FirstName { get; }
		bool IsDeleted { get; }
		string LastName { get; }
		System.DateTime UpdatedDate { get; }
		System.Guid UpdatedUserId { get; }
		System.Guid UserId { get; }

		IUser User_CreatedUserId { get; }
		IUser User_UpdatedUserId { get; }
		List<IBingoContent> BingoContents_UpdatedUserId { get; }
		List<IBingoContent> CreatedUser { get; }
		List<IBingoInstance> BingoInstances_CreatedUserId { get; }
		List<IBingoInstance> BingoInstances_UpdatedUserId { get; }
		List<IBingoInstanceContent> BingoInstanceContents_CreatedUserId { get; }
		List<IBingoInstanceContent> BingoInstanceContents_UpdatedUserId { get; }
		List<IBingoInstanceContent> BingoInstanceContents_UserId { get; }
		List<IBingoInstanceEvent> BingoInstanceEvents_CreatedUserId { get; }
		List<IBingoInstanceEvent> BingoInstanceEvents_UpdatedUserId { get; }
		List<ICompany> Companies_CreatedUserId { get; }
		List<ICompany> Companies_UpdatedUserId { get; }
		List<IMeeting> Meetings_CreatedUserId { get; }
		List<IMeeting> Meetings_UpdatedUserId { get; }
		List<IMeetingAttendee> MeetingAttendees_CreatedUserId { get; }
		List<IMeetingAttendee> MeetingAttendees_UpdatedUserId { get; }
		List<IMeetingAttendee> MeetingAttendees_UserId { get; }
		List<IMeetingSchedule> MeetingSchedules_CreatedUserId { get; }
		List<IMeetingSchedule> MeetingSchedules_UpdatedUserId { get; }
		List<IUser> Users_CreatedUserId { get; }
		List<IUser> Users_UpdatedUserId { get; }


	}
}
